// Code generated by OpenAPI Generator (https://openapi-generator.tech)

/*
 * DotAAS Part 2 | HTTP/REST | Discovery Service Specification
 *
 * The entire Full Profile of the Discovery Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) April 2023
 *
 * API version: V3.0.3_SSP-001
 * Contact: info@idtwin.org
 */

package api

import (
	"context"
	"encoding/json"
	"net/http"
	"time"

	"github.com/google/uuid"

	base64url "github.com/eclipse-basyx/basyx-go-sdk/internal/common"
	"github.com/eclipse-basyx/basyx-go-sdk/internal/discovery/persistence"
	openapi "github.com/eclipse-basyx/basyx-go-sdk/pkg/discoveryapi/go"
)

type contextKey string

const correlationIDKey contextKey = "correlationID"

// Helper function to get or create a correlation ID
func getCorrelationID(ctx context.Context) string {
	if id, ok := ctx.Value(correlationIDKey).(string); ok && id != "" {
		return id
	}
	return uuid.New().String()
}

// AssetAdministrationShellBasicDiscoveryAPIAPIService is a service that implements the logic for the AssetAdministrationShellBasicDiscoveryAPIAPIServicer
// This service should implement the business logic for every endpoint for the AssetAdministrationShellBasicDiscoveryAPIAPI API.
// Include any external packages or services that will be required by this service.
type AssetAdministrationShellBasicDiscoveryAPIAPIService struct {
	database persistence.AasDiscoveryBackend
}

// NewAssetAdministrationShellBasicDiscoveryAPIAPIService creates a default api service
func NewAssetAdministrationShellBasicDiscoveryAPIAPIService(database persistence.AasDiscoveryBackend) *AssetAdministrationShellBasicDiscoveryAPIAPIService {
	return &AssetAdministrationShellBasicDiscoveryAPIAPIService{
		database: database,
	}
}

// GetAllAssetAdministrationShellIdsByAssetLink - Returns a list of Asset Administration Shell ids linked to specific Asset identifiers
func (s *AssetAdministrationShellBasicDiscoveryAPIAPIService) GetAllAssetAdministrationShellIdsByAssetLink(ctx context.Context, assetIds []string, limit int32, cursor string) (openapi.ImplResponse, error) {
	correlationID := getCorrelationID(ctx)

	if len(assetIds) == 0 {
		response := openapi.GetAllAssetAdministrationShellIdsByAssetLink200Response{
			PagingMetadata: openapi.PagedResultPagingMetadata{},
			Result:         []string{},
		}
		return openapi.Response(http.StatusOK, response), nil
	}

	var deserializedAssetIds []openapi.SpecificAssetId
	for i := range assetIds {
		var asset openapi.SpecificAssetId
		decodedString, err := base64url.DecodeString(assetIds[i])
		if err != nil {
			return openapi.Response(http.StatusInternalServerError, openapi.Message{
				Code:          "400",
				MessageType:   "Error",
				Text:          "The provided Asset identifier is not valid.",
				Timestamp:     time.Now().UTC().Format(time.RFC3339),
				CorrelationId: correlationID,
			}), err
		}
		err_unm := json.Unmarshal([]byte(decodedString), &asset)
		if err_unm != nil {
			return openapi.Response(http.StatusInternalServerError, openapi.Message{
				Code:          "400",
				MessageType:   "Error",
				Text:          "The provided Asset identifier is not valid.",
				Timestamp:     time.Now().UTC().Format(time.RFC3339),
				CorrelationId: correlationID,
			}), err_unm
		}
		deserializedAssetIds = append(deserializedAssetIds, asset)
	}

	aasIds, message, cursor := s.database.GetAllAssetAdministrationShellIdsByAssetLink(deserializedAssetIds, limit, cursor)

	if message.Code != "200" {
		message.Timestamp = time.Now().UTC().Format(time.RFC3339)
		message.CorrelationId = correlationID

		statusCode := http.StatusBadRequest
		if message.Code == "404" {
			statusCode = http.StatusNotFound
		} else if message.Code == "400" {
			statusCode = http.StatusBadRequest
		} else {
			statusCode = http.StatusInternalServerError
		}

		return openapi.Response(statusCode, message), nil
	}

	response := openapi.GetAllAssetAdministrationShellIdsByAssetLink200Response{
		PagingMetadata: openapi.PagedResultPagingMetadata{
			Cursor: cursor,
		},
		Result: aasIds,
	}
	return openapi.Response(http.StatusOK, response), nil
}

// GetAllAssetLinksById - Returns a list of specific Asset identifiers based on an Asset Administration Shell id to edit discoverable content
func (s *AssetAdministrationShellBasicDiscoveryAPIAPIService) GetAllAssetLinksById(ctx context.Context, aasIdentifier string) (openapi.ImplResponse, error) {
	correlationID := getCorrelationID(ctx)

	decodedIdentifier, decodeError := base64url.DecodeString(aasIdentifier)
	if decodeError != nil {
		return openapi.Response(http.StatusBadRequest, openapi.Message{
			Code:          "400",
			MessageType:   "Error",
			Text:          "The provided AAS identifier is not valid.",
			Timestamp:     time.Now().UTC().Format(time.RFC3339),
			CorrelationId: correlationID,
		}), decodeError
	}

	links, message := s.database.GetAllAssetLinksById(decodedIdentifier)

	if message.Code != "200" {
		message.Timestamp = time.Now().UTC().Format(time.RFC3339)
		message.CorrelationId = correlationID

		statusCode := http.StatusBadRequest
		if message.Code == "404" {
			statusCode = http.StatusNotFound
		} else if message.Code == "400" {
			statusCode = http.StatusBadRequest
		} else {
			statusCode = http.StatusInternalServerError
		}

		return openapi.Response(statusCode, message), nil
	}

	return openapi.Response(http.StatusOK, links), nil
}

// PostAllAssetLinksById - Creates specific Asset identifiers linked to an Asset Administration Shell to edit discoverable content
func (s *AssetAdministrationShellBasicDiscoveryAPIAPIService) PostAllAssetLinksById(ctx context.Context, aasIdentifier string, specificAssetId []openapi.SpecificAssetId) (openapi.ImplResponse, error) {
	correlationID := getCorrelationID(ctx)

	decodedIdentifier, decodeError := base64url.DecodeString(aasIdentifier)
	if decodeError != nil {
		return openapi.Response(http.StatusBadRequest, openapi.Message{
			Code:          "400",
			MessageType:   "Error",
			Text:          "The provided AAS identifier is not valid.",
			Timestamp:     time.Now().UTC().Format(time.RFC3339),
			CorrelationId: correlationID,
		}), nil
	}

	links, message := s.database.PostAllAssetLinksById(decodedIdentifier, specificAssetId)

	if message.Code != "201" {
		message.Timestamp = time.Now().UTC().Format(time.RFC3339)
		message.CorrelationId = correlationID

		statusCode := http.StatusBadRequest
		if message.Code == "404" {
			statusCode = http.StatusNotFound
		} else if message.Code == "409" {
			statusCode = http.StatusConflict
		} else if message.Code == "400" {
			statusCode = http.StatusBadRequest
		} else {
			statusCode = http.StatusInternalServerError
		}

		return openapi.Response(statusCode, message), nil
	}

	return openapi.Response(http.StatusCreated, links), nil
}

// DeleteAllAssetLinksById - Deletes all specific Asset identifiers linked to an Asset Administration Shell to edit discoverable content
func (s *AssetAdministrationShellBasicDiscoveryAPIAPIService) DeleteAllAssetLinksById(ctx context.Context, aasIdentifier string) (openapi.ImplResponse, error) {
	correlationID := getCorrelationID(ctx)

	decodedIdentifier, decodeError := base64url.DecodeString(aasIdentifier)
	if decodeError != nil {
		return openapi.Response(http.StatusBadRequest, openapi.Message{
			Code:          "400",
			MessageType:   "Error",
			Text:          "The provided AAS identifier is not valid.",
			Timestamp:     time.Now().UTC().Format(time.RFC3339),
			CorrelationId: correlationID,
		}), decodeError
	}

	message := s.database.DeleteAllAssetLinksById(decodedIdentifier)

	if message.Code != "204" {
		message.Timestamp = time.Now().UTC().Format(time.RFC3339)
		message.CorrelationId = correlationID

		statusCode := http.StatusBadRequest
		if message.Code == "404" {
			statusCode = http.StatusNotFound
		} else if message.Code == "400" {
			statusCode = http.StatusBadRequest
		} else {
			statusCode = http.StatusInternalServerError
		}

		return openapi.Response(statusCode, message), nil
	}

	return openapi.Response(http.StatusNoContent, nil), nil
}
